version: 0.0
os: linux
# source는 프로젝트 기준, destination은 instance기준으로 이력
files:
  - source: /
    destination: /home/ubuntu/store-8
    overwrite: yes
permissions:
  - object: /home/ubuntu/store-8
    owner: ubuntu
    group: ubuntu
    mode: 755
hooks:
  AfterInstall:
    - location: scripts/after_deploy.sh # 파일을 올린 후 진행해야하는 작업을 적은 deploy.sh 파일 경로
      timeout: 300
      runas: ubuntu
