export const tempData = [
  {
    isCoupon: true,
    isChecked: true,
    imgLink: 'https://store.baemin.com/data/goods/20/10/44/312/312_list_011.jpg',
    title: '을지로 목장갑, 위잉 뚝딱',
    option: '',
    count: 1,
    amount: 6000,
  },
  {
    isCoupon: true,
    isChecked: true,
    imgLink: 'https://store.baemin.com/data/goods/20/12/50/332/332_list_040.jpg',
    title: '요모포켓X배달이친구들 메이배달이 포켓',
    option: '',
    count: 1,
    amount: 64000,
  },
  {
    isCoupon: true,
    isChecked: true,
    imgLink: 'https://store.baemin.com/data/goods/21/04/14/341/341_list_068.jpg',
    title: '재생지에 콩기름으로 인쇄한 일기장',
    option: '',
    count: 3,
    amount: 3500,
  },
  {
    isCoupon: true,
    isChecked: true,
    imgLink: 'https://store.baemin.com/data/goods/19/11/48/237/237_list_055.png',
    title: 'ㅋㅋ슬리퍼 화이트',
    option: '',
    count: 1,
    amount: 21000,
  },
  {
    isCoupon: false,
    isChecked: true,
    imgLink: 'https://store.baemin.com/data/goods/21/06/22/345/345_list_082.jpg',
    title: '매거진F No.16 Namul',
    option: '',
    count: 1,
    amount: 13500,
  },
];
