type IProductTemp = {
  id: number;
  title: string;
  productImgSrc: string;
  detailImgSrc: string;
  categoryId: number;
  amount: string;
  originalAmount: string;
  sale: number;
};

type IProductIndex = {
  [key: string]: string;
};

type IProductItem = IProductTemp | IProductIndex;

interface IProductConstants {
  [key: string]: IProductItem;
}

export const PRODUCTS: IProductConstants = {
  '1': {
    id: 1,
    title: '티셔츠. 헐',
    productImgSrc: 'public/image/product/big/1.jpg',
    detailImgSrc: 'public/image/product/detail/1.jpg',
    categoryId: 10,
    amount: '23,000',
    originalAmount: '',
    sale: 0,
  },
  '2': {
    id: 2,
    title: '카드케이스. 덮어놓고 긁다보면',
    productImgSrc: 'public/image/product/big/2.jpg',
    detailImgSrc: 'public/image/product/detail/2.jpg',
    categoryId: 2,
    amount: '8,000',
    originalAmount: '',
    sale: 0,
  },
  '3': {
    id: 3,
    title: '마스크. 매너모드',
    productImgSrc: 'public/image/product/big/3.jpg',
    detailImgSrc: 'public/image/product/detail/3.jpg',
    categoryId: 2,
    amount: '8,000',
    originalAmount: '',
    sale: 0,
  },
  '4': {
    id: 4,
    title: '여권케이스. 여행하기 좋은여건 (화이트)',
    productImgSrc: 'public/image/product/big/4.jpg',
    detailImgSrc: 'public/image/product/detail/4.jpg',
    categoryId: 10,
    amount: '12,000',
    originalAmount: '',
    sale: 0,
  },
  '5': {
    id: 5,
    title: '뱃지. 초딩입맛 외 10종',
    productImgSrc: 'public/image/product/big/5.jpg',
    detailImgSrc: 'public/image/product/detail/5.jpg',
    categoryId: 10,
    amount: '1,500',
    originalAmount: '',
    sale: 0,
  },
  '6': {
    id: 6,
    title: '캐리어벨트. ㅋㅋㅋ',
    productImgSrc: 'public/image/product/big/6.jpg',
    detailImgSrc: 'public/image/product/detail/6.jpg',
    categoryId: 10,
    amount: '16,000',
    originalAmount: '',
    sale: 0,
  },
  '7': {
    id: 7,
    title: '수건. 너 먼저 씻어',
    productImgSrc: 'public/image/product/big/7.jpg',
    detailImgSrc: 'public/image/product/detail/7.jpg',
    categoryId: 2,
    amount: '9,900',
    originalAmount: '',
    sale: 0,
  },
  '8': {
    id: 8,
    title: '팝소켓. 뾱',
    productImgSrc: 'public/image/product/big/8.jpg',
    detailImgSrc: 'public/image/product/detail/8.jpg',
    categoryId: 10,
    amount: '11,900',
    originalAmount: '',
    sale: 0,
  },
  '9': {
    id: 9,
    title: '티셔츠. 연애중이면좋겠다',
    productImgSrc: 'public/image/product/big/9.jpg',
    detailImgSrc: 'public/image/product/detail/9.jpg',
    categoryId: 10,
    amount: '23,000',
    originalAmount: '',
    sale: 0,
  },
  '10': {
    id: 10,
    title: '연필꽂이. 머그컵같은연필꽂이',
    productImgSrc: 'public/image/product/big/10.jpg',
    detailImgSrc: 'public/image/product/detail/10.jpg',
    categoryId: 2,
    amount: '9,000',
    originalAmount: '',
    sale: 0,
  },
  '11': {
    id: 11,
    title: '노트. 연애중이면 좋겠다',
    productImgSrc: 'public/image/product/big/11.jpg',
    detailImgSrc: 'public/image/product/detail/11.jpg',
    categoryId: 10,
    amount: '2,500',
    originalAmount: '',
    sale: 0,
  },
  '12': {
    id: 12,
    title: '노트. 살찌는 것은 죄가 아니다',
    productImgSrc: 'public/image/product/big/12.jpg',
    detailImgSrc: 'public/image/product/detail/12.jpg',
    categoryId: 10,
    amount: '2,500',
    originalAmount: '',
    sale: 0,
  },
  '13': {
    id: 13,
    title: '노트. 굿',
    productImgSrc: 'public/image/product/big/13.jpg',
    detailImgSrc: 'public/image/product/detail/13.jpg',
    categoryId: 1,
    amount: '2,500',
    originalAmount: '',
    sale: 0,
  },
  '14': {
    id: 14,
    title: 'USB. 이런십육기가',
    productImgSrc: 'public/image/product/big/14.jpg',
    detailImgSrc: 'public/image/product/detail/14.jpg',
    categoryId: 1,
    amount: '38,000',
    originalAmount: '',
    sale: 0,
  },
  '15': {
    id: 15,
    title: '미니카드. 배고프니까 청춘이다',
    productImgSrc: 'public/image/product/big/15.jpg',
    detailImgSrc: 'public/image/product/detail/15.jpg',
    categoryId: 10,
    amount: '1,500',
    originalAmount: '',
    sale: 0,
  },
  '16': {
    id: 16,
    title: '미니카드. 살찌는 것은 죄가 아니다',
    productImgSrc: 'public/image/product/big/16.jpg',
    detailImgSrc: 'public/image/product/detail/16.jpg',
    categoryId: 10,
    amount: '1,500',
    originalAmount: '',
    sale: 0,
  },
  '17': {
    id: 17,
    title: '노트. 청소를 안하면',
    productImgSrc: 'public/image/product/big/17.jpg',
    detailImgSrc: 'public/image/product/detail/17.jpg',
    categoryId: 1,
    amount: '2,500',
    originalAmount: '',
    sale: 0,
  },
  '18': {
    id: 18,
    title: '노트. 헐',
    productImgSrc: 'public/image/product/big/18.jpg',
    detailImgSrc: 'public/image/product/detail/18.jpg',
    categoryId: 1,
    amount: '2,500',
    originalAmount: '',
    sale: 0,
  },
  '19': {
    id: 19,
    title: '노트. 씻고자자',
    productImgSrc: 'public/image/product/big/19.jpg',
    detailImgSrc: 'public/image/product/detail/19.jpg',
    categoryId: 1,
    amount: '2,500',
    originalAmount: '',
    sale: 0,
  },
  '20': {
    id: 20,
    title: '볼펜. 나도 언젠간 쓸데가 있겠지',
    productImgSrc: 'public/image/product/big/20.jpg',
    detailImgSrc: 'public/image/product/detail/20.jpg',
    categoryId: 1,
    amount: '2,000',
    originalAmount: '',
    sale: 0,
  },
  '21': {
    id: 21,
    title: '손거울. 거울에 보이는것보다 이뻐요~',
    productImgSrc: 'public/image/product/big/21.jpg',
    detailImgSrc: 'public/image/product/detail/21.jpg',
    categoryId: 10,
    amount: '8,000',
    originalAmount: '',
    sale: 0,
  },
  '22': {
    id: 22,
    title: '에코백. 난너의든든한빽',
    productImgSrc: 'public/image/product/big/22.jpg',
    detailImgSrc: 'public/image/product/detail/22.jpg',
    categoryId: 10,
    amount: '15,000',
    originalAmount: '',
    sale: 0,
  },
  '23': {
    id: 23,
    title: '엽서. 헐',
    productImgSrc: 'public/image/product/big/23.jpg',
    detailImgSrc: 'public/image/product/detail/23.jpg',
    categoryId: 10,
    amount: '1,000',
    originalAmount: '',
    sale: 0,
  },
  '24': {
    id: 24,
    title: '엽서. 배고프니까 청춘이다',
    productImgSrc: 'public/image/product/big/24.jpg',
    detailImgSrc: 'public/image/product/detail/24.jpg',
    categoryId: 10,
    amount: '1,000',
    originalAmount: '',
    sale: 0,
  },
  '25': {
    id: 25,
    title: '엽서. 살찌는 것은 죄가 아니다',
    productImgSrc: 'public/image/product/big/25.jpg',
    detailImgSrc: 'public/image/product/detail/25.jpg',
    categoryId: 10,
    amount: '1,000',
    originalAmount: '',
    sale: 0,
  },
  '26': {
    id: 26,
    title: '티셔츠. 이끌든지 따르든지 비키든지',
    productImgSrc: 'public/image/product/big/26.jpg',
    detailImgSrc: 'public/image/product/detail/26.jpg',
    categoryId: 10,
    amount: '23,000',
    originalAmount: '',
    sale: 0,
  },
  '27': {
    id: 27,
    title: '클리너. 닦으면 비로소 보이는 것들',
    productImgSrc: 'public/image/product/big/27.jpg',
    detailImgSrc: 'public/image/product/detail/27.jpg',
    categoryId: 2,
    amount: '3,500',
    originalAmount: '',
    sale: 0,
  },
  '28': {
    id: 28,
    title: '파일. 교수님 사랑해요',
    productImgSrc: 'public/image/product/big/28.jpg',
    detailImgSrc: 'public/image/product/detail/28.jpg',
    categoryId: 1,
    amount: '1,500',
    originalAmount: '',
    sale: 0,
  },
  '29': {
    id: 29,
    title: '파일. 사장님이 최고예요',
    productImgSrc: 'public/image/product/big/29.jpg',
    detailImgSrc: 'public/image/product/detail/29.jpg',
    categoryId: 1,
    amount: '1,500',
    originalAmount: '',
    sale: 0,
  },
  '30': {
    id: 30,
    title: '(구.)볼펜세트. 어머 펜이에요~',
    productImgSrc: 'public/image/product/big/30.jpg',
    detailImgSrc: 'public/image/product/detail/30.jpg',
    categoryId: 10,
    amount: '3,500',
    originalAmount: '',
    sale: 0,
  },
  '31': {
    id: 31,
    title: '메모잇. 까먹지 말자',
    productImgSrc: 'public/image/product/big/31.jpg',
    detailImgSrc: 'public/image/product/detail/31.jpg',
    categoryId: 1,
    amount: '2,000',
    originalAmount: '',
    sale: 0,
  },
  '32': {
    id: 32,
    title: '티셔츠. 살찌는것은 죄가 아니다',
    productImgSrc: 'public/image/product/big/32.jpg',
    detailImgSrc: 'public/image/product/detail/32.jpg',
    categoryId: 10,
    amount: '23,000',
    originalAmount: '',
    sale: 0,
  },
  '33': {
    id: 33,
    title: '때수건. 다 때가 있다',
    productImgSrc: 'public/image/product/big/33.jpg',
    detailImgSrc: 'public/image/product/detail/33.jpg',
    categoryId: 2,
    amount: '2,000',
    originalAmount: '',
    sale: 0,
  },
  '34': {
    id: 34,
    title: '담요. 외롭지않아, 단지 추울뿐',
    productImgSrc: 'public/image/product/big/34.jpg',
    detailImgSrc: 'public/image/product/detail/34.jpg',
    categoryId: 10,
    amount: '15,000',
    originalAmount: '',
    sale: 0,
  },
  '35': {
    id: 35,
    title: '포스터. 배고프니까 청춘 외 16종',
    productImgSrc: 'public/image/product/big/35.jpg',
    detailImgSrc: 'public/image/product/detail/35.jpg',
    categoryId: 10,
    amount: '3,000',
    originalAmount: '',
    sale: 0,
  },
  '36': {
    id: 36,
    title: '네임택. 찜 (화이트)',
    productImgSrc: 'public/image/product/big/36.jpg',
    detailImgSrc: 'public/image/product/detail/36.jpg',
    categoryId: 2,
    amount: '3,000',
    originalAmount: '',
    sale: 0,
  },
  '37': {
    id: 37,
    title: '돗자리. 앉으면 내땅',
    productImgSrc: 'public/image/product/big/37.jpg',
    detailImgSrc: 'public/image/product/detail/37.jpg',
    categoryId: 2,
    amount: '3,000',
    originalAmount: '',
    sale: 0,
  },
  '38': {
    id: 38,
    title: '맨투맨. 헐',
    productImgSrc: 'public/image/product/big/38.jpg',
    detailImgSrc: 'public/image/product/detail/38.jpg',
    categoryId: 10,
    amount: '38,000',
    originalAmount: '',
    sale: 0,
  },
  '39': {
    id: 39,
    title: '미니카드. 굿',
    productImgSrc: 'public/image/product/big/39.jpg',
    detailImgSrc: 'public/image/product/detail/39.jpg',
    categoryId: 10,
    amount: '1,500',
    originalAmount: '',
    sale: 0,
  },
  '40': {
    id: 40,
    title: '지우개. 내 번호 지우지마',
    productImgSrc: 'public/image/product/big/40.jpg',
    detailImgSrc: 'public/image/product/detail/40.jpg',
    categoryId: 1,
    amount: '1,500',
    originalAmount: '',
    sale: 0,
  },
  '41': {
    id: 41,
    title: '양말. 내짝은 어디에',
    productImgSrc: 'public/image/product/big/41.jpg',
    detailImgSrc: 'public/image/product/detail/41.jpg',
    categoryId: 10,
    amount: '3,500',
    originalAmount: '',
    sale: 0,
  },
  '42': {
    id: 42,
    title: '양말. 왼발오른발',
    productImgSrc: 'public/image/product/big/42.jpg',
    detailImgSrc: 'public/image/product/detail/42.jpg',
    categoryId: 10,
    amount: '3,500',
    originalAmount: '',
    sale: 0,
  },
  '43': {
    id: 43,
    title: '파일. 팀장님 짱짱맨',
    productImgSrc: 'public/image/product/big/43.jpg',
    detailImgSrc: 'public/image/product/detail/43.jpg',
    categoryId: 1,
    amount: '1,500',
    originalAmount: '',
    sale: 0,
  },
  '44': {
    id: 44,
    title: '미니노트세트(5개입)',
    productImgSrc: 'public/image/product/big/44.jpg',
    detailImgSrc: 'public/image/product/detail/44.jpg',
    categoryId: 10,
    amount: '4,500',
    originalAmount: '',
    sale: 0,
  },
  '45': {
    id: 45,
    title: '링노트. 이끌든지 따르든지 비키든지',
    productImgSrc: 'public/image/product/big/45.jpg',
    detailImgSrc: 'public/image/product/detail/45.jpg',
    categoryId: 1,
    amount: '2,000',
    originalAmount: '',
    sale: 0,
  },
  '46': {
    id: 46,
    title: '링노트. 청소를 안하면',
    productImgSrc: 'public/image/product/big/46.jpg',
    detailImgSrc: 'public/image/product/detail/46.jpg',
    categoryId: 1,
    amount: '2,000',
    originalAmount: '',
    sale: 0,
  },
  '47': {
    id: 47,
    title: '링노트. 헐',
    productImgSrc: 'public/image/product/big/47.jpg',
    detailImgSrc: 'public/image/product/detail/47.jpg',
    categoryId: 1,
    amount: '2,000',
    originalAmount: '',
    sale: 0,
  },
  '48': {
    id: 48,
    title: '링노트. 오늘 먹을 치킨',
    productImgSrc: 'public/image/product/big/48.jpg',
    detailImgSrc: 'public/image/product/detail/48.jpg',
    categoryId: 1,
    amount: '2,000',
    originalAmount: '',
    sale: 0,
  },
  '49': {
    id: 49,
    title: '링노트. 못해솔로',
    productImgSrc: 'public/image/product/big/49.jpg',
    detailImgSrc: 'public/image/product/detail/49.jpg',
    categoryId: 10,
    amount: '2,000',
    originalAmount: '',
    sale: 0,
  },
  '50': {
    id: 50,
    title: '여권케이스. 여행하기 좋은여건 (블랙)',
    productImgSrc: 'public/image/product/big/50.jpg',
    detailImgSrc: 'public/image/product/detail/50.jpg',
    categoryId: 10,
    amount: '12,000',
    originalAmount: '',
    sale: 0,
  },
  '51': {
    id: 51,
    title: '목베개. 여기목좋아요',
    productImgSrc: 'public/image/product/big/51.jpg',
    detailImgSrc: 'public/image/product/detail/51.jpg',
    categoryId: 2,
    amount: '12,000',
    originalAmount: '',
    sale: 0,
  },
  '52': {
    id: 52,
    title: '네임택. 찜 (블랙)',
    productImgSrc: 'public/image/product/big/52.jpg',
    detailImgSrc: 'public/image/product/detail/52.jpg',
    categoryId: 2,
    amount: '4,500',
    originalAmount: '',
    sale: 0,
  },
  '53': {
    id: 53,
    title: '부채. 수동바람 태풍바람',
    productImgSrc: 'public/image/product/big/53.jpg',
    detailImgSrc: 'public/image/product/detail/53.jpg',
    categoryId: 2,
    amount: '4,500',
    originalAmount: '',
    sale: 0,
  },
  '54': {
    id: 54,
    title: '부채. 힘에부침 셀프냉방',
    productImgSrc: 'public/image/product/big/54.jpg',
    detailImgSrc: 'public/image/product/detail/54.jpg',
    categoryId: 2,
    amount: '4,500',
    originalAmount: '',
    sale: 0,
  },
  '55': {
    id: 55,
    title: '안대. 깨우면안대',
    productImgSrc: 'public/image/product/big/55.jpg',
    detailImgSrc: 'public/image/product/detail/55.jpg',
    categoryId: 2,
    amount: '4,500',
    originalAmount: '',
    sale: 0,
  },
  '56': {
    id: 56,
    title: '연필. 흑심있어요',
    productImgSrc: 'public/image/product/big/56.jpg',
    detailImgSrc: 'public/image/product/detail/56.jpg',
    categoryId: 1,
    amount: '1,000',
    originalAmount: '',
    sale: 0,
  },
  '57': {
    id: 57,
    title: '맨투맨. 헐 블랙',
    productImgSrc: 'public/image/product/big/57.jpg',
    detailImgSrc: 'public/image/product/detail/57.jpg',
    categoryId: 10,
    amount: '38,000',
    originalAmount: '',
    sale: 0,
  },
  '58': {
    id: 58,
    title: '미니카드. 효도하자',
    productImgSrc: 'public/image/product/big/58.jpg',
    detailImgSrc: 'public/image/product/detail/58.jpg',
    categoryId: 10,
    amount: '1,500',
    originalAmount: '',
    sale: 0,
  },
  '59': {
    id: 59,
    title: '엽서. 청소를 안하면',
    productImgSrc: 'public/image/product/big/59.jpg',
    detailImgSrc: 'public/image/product/detail/59.jpg',
    categoryId: 10,
    amount: '1,000',
    originalAmount: '',
    sale: 0,
  },
  '60': {
    id: 60,
    title: '엽서. 굿(원형)',
    productImgSrc: 'public/image/product/big/60.jpg',
    detailImgSrc: 'public/image/product/detail/60.jpg',
    categoryId: 10,
    amount: '1,000',
    originalAmount: '',
    sale: 0,
  },
  '61': {
    id: 61,
    title: '엽서. 오늘먹을치킨을',
    productImgSrc: 'public/image/product/big/61.jpg',
    detailImgSrc: 'public/image/product/detail/61.jpg',
    categoryId: 10,
    amount: '1,000',
    originalAmount: '',
    sale: 0,
  },
  '62': {
    id: 62,
    title: '비치볼. 나잡아봐라',
    productImgSrc: 'public/image/product/big/62.jpg',
    detailImgSrc: 'public/image/product/detail/62.jpg',
    categoryId: 2,
    amount: '1,000',
    originalAmount: '',
    sale: 0,
  },
  '63': {
    id: 63,
    title: '튜브. 니가 자꾸 떠올라',
    productImgSrc: 'public/image/product/big/63.jpg',
    detailImgSrc: 'public/image/product/detail/63.jpg',
    categoryId: 2,
    amount: '1,000',
    originalAmount: '',
    sale: 0,
  },
  '64': {
    id: 64,
    title: '방수팩. 방수모드',
    productImgSrc: 'public/image/product/big/64.jpg',
    detailImgSrc: 'public/image/product/detail/64.jpg',
    categoryId: 10,
    amount: '5,500',
    originalAmount: '',
    sale: 0,
  },
  '65': {
    id: 65,
    title: '지퍼백. 닦고자자',
    productImgSrc: 'public/image/product/big/65.jpg',
    detailImgSrc: 'public/image/product/detail/65.jpg',
    categoryId: 2,
    amount: '5,500',
    originalAmount: '',
    sale: 0,
  },
  '66': {
    id: 66,
    title: '미니선풍기. 나의작은바람',
    productImgSrc: 'public/image/product/big/66.jpg',
    detailImgSrc: 'public/image/product/detail/66.jpg',
    categoryId: 10,
    amount: '4,500',
    originalAmount: '',
    sale: 0,
  },
  '67': {
    id: 67,
    title: '비치타월. 누가나좀말려줘요',
    productImgSrc: 'public/image/product/big/67.jpg',
    detailImgSrc: 'public/image/product/detail/67.jpg',
    categoryId: 2,
    amount: '4,500',
    originalAmount: '',
    sale: 0,
  },
  '68': {
    id: 68,
    title: '접기 편한 돗자리. 앉으면내땅',
    productImgSrc: 'public/image/product/big/68.jpg',
    detailImgSrc: 'public/image/product/detail/68.jpg',
    categoryId: 2,
    amount: '8,000',
    originalAmount: '',
    sale: 0,
  },
  '69': {
    id: 69,
    title: '포켓 돗자리. 앉으면내땅',
    productImgSrc: 'public/image/product/big/69.jpg',
    detailImgSrc: 'public/image/product/detail/69.jpg',
    categoryId: 2,
    amount: '15,900',
    originalAmount: '',
    sale: 0,
  },
  '70': {
    id: 70,
    title: '지퍼백. 청소를안하면',
    productImgSrc: 'public/image/product/big/70.jpg',
    detailImgSrc: 'public/image/product/detail/70.jpg',
    categoryId: 2,
    amount: '15,900',
    originalAmount: '',
    sale: 0,
  },
  '71': {
    id: 71,
    title: '지퍼백. 씻고자자',
    productImgSrc: 'public/image/product/big/71.jpg',
    detailImgSrc: 'public/image/product/detail/71.jpg',
    categoryId: 2,
    amount: '15,900',
    originalAmount: '',
    sale: 0,
  },
  '72': {
    id: 72,
    title: '엽서. 축',
    productImgSrc: 'public/image/product/big/72.jpg',
    detailImgSrc: 'public/image/product/detail/72.jpg',
    categoryId: 1,
    amount: '1,000',
    originalAmount: '',
    sale: 0,
  },
  '73': {
    id: 73,
    title: '돈봉투. 감사',
    productImgSrc: 'public/image/product/big/73.jpg',
    detailImgSrc: 'public/image/product/detail/73.jpg',
    categoryId: 1,
    amount: '2,500',
    originalAmount: '',
    sale: 0,
  },
  '74': {
    id: 74,
    title: '엽서. 굿',
    productImgSrc: 'public/image/product/big/74.jpg',
    detailImgSrc: 'public/image/product/detail/74.jpg',
    categoryId: 1,
    amount: '1,000',
    originalAmount: '',
    sale: 0,
  },
  '75': {
    id: 75,
    title: '엽서. 복',
    productImgSrc: 'public/image/product/big/75.jpg',
    detailImgSrc: 'public/image/product/detail/75.jpg',
    categoryId: 1,
    amount: '1,000',
    originalAmount: '',
    sale: 0,
  },
  '76': {
    id: 76,
    title: '에코백. 난너의든든한빽 (블랙)',
    productImgSrc: 'public/image/product/big/76.jpg',
    detailImgSrc: 'public/image/product/detail/76.jpg',
    categoryId: 10,
    amount: '15,000',
    originalAmount: '',
    sale: 0,
  },
  '77': {
    id: 77,
    title: '맥주잔. 비워도다시한번',
    productImgSrc: 'public/image/product/big/77.jpg',
    detailImgSrc: 'public/image/product/detail/77.jpg',
    categoryId: 2,
    amount: '15,000',
    originalAmount: '',
    sale: 0,
  },
  '78': {
    id: 78,
    title: 'CU X 배달의민족. 흔드는 핫팩',
    productImgSrc: 'public/image/product/big/78.jpg',
    detailImgSrc: 'public/image/product/detail/78.jpg',
    categoryId: 9,
    amount: '15,000',
    originalAmount: '',
    sale: 0,
  },
  '79': {
    id: 79,
    title: 'CU X 배달의민족. 붙이는 핫팩',
    productImgSrc: 'public/image/product/big/79.jpg',
    detailImgSrc: 'public/image/product/detail/79.jpg',
    categoryId: 9,
    amount: '15,000',
    originalAmount: '',
    sale: 0,
  },
  '80': {
    id: 80,
    title: '(구.) 컴퓨터싸인펜. 오늘이 전설이 될 것이다',
    productImgSrc: 'public/image/product/big/80.jpg',
    detailImgSrc: 'public/image/product/detail/80.jpg',
    categoryId: 10,
    amount: '1,000',
    originalAmount: '',
    sale: 0,
  },
  '81': {
    id: 81,
    title: '2017 일력. 365일 잘먹고 잘살자',
    productImgSrc: 'public/image/product/big/81.jpg',
    detailImgSrc: 'public/image/product/detail/81.jpg',
    categoryId: 10,
    amount: '1,000',
    originalAmount: '',
    sale: 0,
  },
  '82': {
    id: 82,
    title: '스티커. 취급주의',
    productImgSrc: 'public/image/product/big/82.jpg',
    detailImgSrc: 'public/image/product/detail/82.jpg',
    categoryId: 1,
    amount: '1,500',
    originalAmount: '',
    sale: 0,
  },
  '83': {
    id: 83,
    title: '열쇠고리.헐',
    productImgSrc: 'public/image/product/big/83.jpg',
    detailImgSrc: 'public/image/product/detail/83.jpg',
    categoryId: 2,
    amount: '1,500',
    originalAmount: '',
    sale: 0,
  },
  '84': {
    id: 84,
    title: 'USB. 이런십육기가',
    productImgSrc: 'public/image/product/big/84.jpg',
    detailImgSrc: 'public/image/product/detail/84.jpg',
    categoryId: 1,
    amount: '1,500',
    originalAmount: '',
    sale: 0,
  },
  '85': {
    id: 85,
    title: '레터링시트지. 지켜보고 있다',
    productImgSrc: 'public/image/product/big/85.jpg',
    detailImgSrc: 'public/image/product/detail/85.jpg',
    categoryId: 2,
    amount: '4,000',
    originalAmount: '',
    sale: 0,
  },
  '86': {
    id: 86,
    title: '박스테이프. 두근두근',
    productImgSrc: 'public/image/product/big/86.jpg',
    detailImgSrc: 'public/image/product/detail/86.jpg',
    categoryId: 1,
    amount: '4,500',
    originalAmount: '',
    sale: 0,
  },
  '87': {
    id: 87,
    title: '파티픽 세트',
    productImgSrc: 'public/image/product/big/87.jpg',
    detailImgSrc: 'public/image/product/detail/87.jpg',
    categoryId: 2,
    amount: '2,500',
    originalAmount: '',
    sale: 0,
  },
  '88': {
    id: 88,
    title: '축구공. 뻥',
    productImgSrc: 'public/image/product/big/88.jpg',
    detailImgSrc: 'public/image/product/detail/88.jpg',
    categoryId: 9,
    amount: '2,500',
    originalAmount: '',
    sale: 0,
  },
  '89': {
    id: 89,
    title: '돈봉투 골드에디션. 용돈',
    productImgSrc: 'public/image/product/big/89.jpg',
    detailImgSrc: 'public/image/product/detail/89.jpg',
    categoryId: 1,
    amount: '3,500',
    originalAmount: '',
    sale: 0,
  },
  '90': {
    id: 90,
    title: '마스킹테이프 set',
    productImgSrc: 'public/image/product/big/90.jpg',
    detailImgSrc: 'public/image/product/detail/90.jpg',
    categoryId: 1,
    amount: '3,900',
    originalAmount: '',
    sale: 0,
  },
  '91': {
    id: 91,
    title: '뱃지. 치킨',
    productImgSrc: 'public/image/product/big/91.jpg',
    detailImgSrc: 'public/image/product/detail/91.jpg',
    categoryId: 2,
    amount: '5,500',
    originalAmount: '',
    sale: 0,
  },
  '92': {
    id: 92,
    title: '뱃지. 피자',
    productImgSrc: 'public/image/product/big/92.jpg',
    detailImgSrc: 'public/image/product/detail/92.jpg',
    categoryId: 2,
    amount: '5,500',
    originalAmount: '',
    sale: 0,
  },
  '93': {
    id: 93,
    title: '생활공감 에코백. 제가요',
    productImgSrc: 'public/image/product/big/93.jpg',
    detailImgSrc: 'public/image/product/detail/93.jpg',
    categoryId: 2,
    amount: '15,000',
    originalAmount: '',
    sale: 0,
  },
  '94': {
    id: 94,
    title: '락앤락 X 배달의민족. 용기가 필요해',
    productImgSrc: 'public/image/product/big/94.jpg',
    detailImgSrc: 'public/image/product/detail/94.jpg',
    categoryId: 9,
    amount: '15,000',
    originalAmount: '',
    sale: 0,
  },
  '95': {
    id: 95,
    title: '72초TV. 까마귀상가 법전키트',
    productImgSrc: 'public/image/product/big/95.jpg',
    detailImgSrc: 'public/image/product/detail/95.jpg',
    categoryId: 10,
    amount: '15,000',
    originalAmount: '',
    sale: 0,
  },
  '96': {
    id: 96,
    title: '배민다움',
    productImgSrc: 'public/image/product/big/96.jpg',
    detailImgSrc: 'public/image/product/detail/96.jpg',
    categoryId: 3,
    amount: '15,000',
    originalAmount: '',
    sale: 0,
  },
  '97': {
    id: 97,
    title: '생활공감 노트. 제가요',
    productImgSrc: 'public/image/product/big/97.jpg',
    detailImgSrc: 'public/image/product/detail/97.jpg',
    categoryId: 1,
    amount: '2,500',
    originalAmount: '',
    sale: 0,
  },
  '98': {
    id: 98,
    title: '이천십칠 배민다이어리',
    productImgSrc: 'public/image/product/big/98.jpg',
    detailImgSrc: 'public/image/product/detail/98.jpg',
    categoryId: 10,
    amount: '2,500',
    originalAmount: '',
    sale: 0,
  },
  '99': {
    id: 99,
    title: '배짱이 1기, 2기 스페셜패키지',
    productImgSrc: 'public/image/product/big/99.jpg',
    detailImgSrc: 'public/image/product/detail/99.jpg',
    categoryId: 10,
    amount: '2,500',
    originalAmount: '',
    sale: 0,
  },
  '100': {
    id: 100,
    title: '제 1회 배민 치믈리에 자격시험',
    productImgSrc: 'public/image/product/big/100.jpg',
    detailImgSrc: 'public/image/product/detail/100.jpg',
    categoryId: 10,
    amount: '2,500',
    originalAmount: '',
    sale: 0,
  },
  '101': {
    id: 101,
    title: '파티컵세트 (10입)',
    productImgSrc: 'public/image/product/big/101.jpg',
    detailImgSrc: 'public/image/product/detail/101.jpg',
    categoryId: 10,
    amount: '3,000',
    originalAmount: '',
    sale: 0,
  },
  '102': {
    id: 102,
    title: '쇼핑백. 뭘 이런걸 다',
    productImgSrc: 'public/image/product/big/102.jpg',
    detailImgSrc: 'public/image/product/detail/102.jpg',
    categoryId: 10,
    amount: '1,500',
    originalAmount: '',
    sale: 0,
  },
  '103': {
    id: 103,
    title: '배민문방구 황금연휴 배송지연공지',
    productImgSrc: 'public/image/product/big/103.jpg',
    detailImgSrc: 'public/image/product/detail/103.jpg',
    categoryId: 10,
    amount: '1,500',
    originalAmount: '',
    sale: 0,
  },
  '104': {
    id: 104,
    title: '오늘은 불닭볶음면이 땡긴다',
    productImgSrc: 'public/image/product/big/104.jpg',
    detailImgSrc: 'public/image/product/detail/104.jpg',
    categoryId: 9,
    amount: '1,500',
    originalAmount: '',
    sale: 0,
  },
  '105': {
    id: 105,
    title: '목욕감 목욕선물세트',
    productImgSrc: 'public/image/product/big/105.jpg',
    detailImgSrc: 'public/image/product/detail/105.jpg',
    categoryId: 9,
    amount: '1,500',
    originalAmount: '',
    sale: 0,
  },
  '106': {
    id: 106,
    title: '이빨청춘 칫솔치약세트',
    productImgSrc: 'public/image/product/big/106.jpg',
    detailImgSrc: 'public/image/product/detail/106.jpg',
    categoryId: 9,
    amount: '1,500',
    originalAmount: '',
    sale: 0,
  },
  '107': {
    id: 107,
    title: 'CU X 배달의민족. 여행용세트',
    productImgSrc: 'public/image/product/big/107.jpg',
    detailImgSrc: 'public/image/product/detail/107.jpg',
    categoryId: 9,
    amount: '1,500',
    originalAmount: '',
    sale: 0,
  },
  '108': {
    id: 108,
    title: '2018 일력. 날이면 날마다',
    productImgSrc: 'public/image/product/big/108.jpg',
    detailImgSrc: 'public/image/product/detail/108.jpg',
    categoryId: 10,
    amount: '1,500',
    originalAmount: '',
    sale: 0,
  },
  '109': {
    id: 109,
    title: '레터링시트지. 쉽고, 명확하고, 위트있게',
    productImgSrc: 'public/image/product/big/109.jpg',
    detailImgSrc: 'public/image/product/detail/109.jpg',
    categoryId: 2,
    amount: '4,000',
    originalAmount: '',
    sale: 0,
  },
  '110': {
    id: 110,
    title: 'CU X 배달의민족. 방한용품 8종',
    productImgSrc: 'public/image/product/big/110.jpg',
    detailImgSrc: 'public/image/product/detail/110.jpg',
    categoryId: 9,
    amount: '4,000',
    originalAmount: '',
    sale: 0,
  },
  '111': {
    id: 111,
    title: '배민문방구 새해선물세트',
    productImgSrc: 'public/image/product/big/111.jpg',
    detailImgSrc: 'public/image/product/detail/111.jpg',
    categoryId: 10,
    amount: '4,000',
    originalAmount: '',
    sale: 0,
  },
  '112': {
    id: 112,
    title: '똑똑똑 실내홥니다',
    productImgSrc: 'public/image/product/big/112.jpg',
    detailImgSrc: 'public/image/product/detail/112.jpg',
    categoryId: 9,
    amount: '4,000',
    originalAmount: '',
    sale: 0,
  },
  '113': {
    id: 113,
    title: '치약. 이빨청춘',
    productImgSrc: 'public/image/product/big/113.jpg',
    detailImgSrc: 'public/image/product/detail/113.jpg',
    categoryId: 9,
    amount: '4,000',
    originalAmount: '',
    sale: 0,
  },
  '114': {
    id: 114,
    title: '칫솔. 이쓸 때 잘해',
    productImgSrc: 'public/image/product/big/114.jpg',
    detailImgSrc: 'public/image/product/detail/114.jpg',
    categoryId: 9,
    amount: '4,000',
    originalAmount: '',
    sale: 0,
  },
  '115': {
    id: 115,
    title: '세븐일레븐X배달의민족. 웃기는젤리',
    productImgSrc: 'public/image/product/big/115.jpg',
    detailImgSrc: 'public/image/product/detail/115.jpg',
    categoryId: 9,
    amount: '4,000',
    originalAmount: '',
    sale: 0,
  },
  '116': {
    id: 116,
    title: '매거진F No.01 salt 스페셜 패키지',
    productImgSrc: 'public/image/product/big/116.jpg',
    detailImgSrc: 'public/image/product/detail/116.jpg',
    categoryId: 3,
    amount: '4,000',
    originalAmount: '',
    sale: 0,
  },
  '117': {
    id: 117,
    title: '돈봉투 블랙에디션. 용돈',
    productImgSrc: 'public/image/product/big/117.jpg',
    detailImgSrc: 'public/image/product/detail/117.jpg',
    categoryId: 10,
    amount: '2,500',
    originalAmount: '',
    sale: 0,
  },
  '118': {
    id: 118,
    title: '넛때문이야. 아몬드',
    productImgSrc: 'public/image/product/big/118.jpg',
    detailImgSrc: 'public/image/product/detail/118.jpg',
    categoryId: 9,
    amount: '2,500',
    originalAmount: '',
    sale: 0,
  },
  '119': {
    id: 119,
    title: '배짱이 3기 스페셜패키지',
    productImgSrc: 'public/image/product/big/119.jpg',
    detailImgSrc: 'public/image/product/detail/119.jpg',
    categoryId: 10,
    amount: '2,500',
    originalAmount: '',
    sale: 0,
  },
  '120': {
    id: 120,
    title: '[한정판] 배짱이 노트 set',
    productImgSrc: 'public/image/product/big/120.jpg',
    detailImgSrc: 'public/image/product/detail/120.jpg',
    categoryId: 10,
    amount: '4,500',
    originalAmount: '',
    sale: 0,
  },
  '121': {
    id: 121,
    title: '[한정판] 배짱이 레터링시트지 set',
    productImgSrc: 'public/image/product/big/121.jpg',
    detailImgSrc: 'public/image/product/detail/121.jpg',
    categoryId: 10,
    amount: '5,000',
    originalAmount: '',
    sale: 0,
  },
  '122': {
    id: 122,
    title: '[한정판] 배짱이 돗자리',
    productImgSrc: 'public/image/product/big/122.jpg',
    detailImgSrc: 'public/image/product/detail/122.jpg',
    categoryId: 10,
    amount: '11,900',
    originalAmount: '',
    sale: 0,
  },
  '123': {
    id: 123,
    title: '맥주짠 세트',
    productImgSrc: 'public/image/product/big/123.jpg',
    detailImgSrc: 'public/image/product/detail/123.jpg',
    categoryId: 8,
    amount: '10,900',
    originalAmount: '',
    sale: 0,
  },
  '124': {
    id: 124,
    title: '매거진F No.01 salt',
    productImgSrc: 'public/image/product/big/124.jpg',
    detailImgSrc: 'public/image/product/detail/124.jpg',
    categoryId: 3,
    amount: '13,500',
    originalAmount: '15,000',
    sale: 10,
  },
  '125': {
    id: 125,
    title: '보드마카. 막상마카',
    productImgSrc: 'public/image/product/big/125.jpg',
    detailImgSrc: 'public/image/product/detail/125.jpg',
    categoryId: 10,
    amount: '13,500',
    originalAmount: '',
    sale: 0,
  },
  '126': {
    id: 126,
    title: '캐리어커버. 짐캐리',
    productImgSrc: 'public/image/product/big/126.jpg',
    detailImgSrc: 'public/image/product/detail/126.jpg',
    categoryId: 10,
    amount: '13,500',
    originalAmount: '',
    sale: 0,
  },
  '127': {
    id: 127,
    title: '세븐일레븐X배달의민족. 얼음땡',
    productImgSrc: 'public/image/product/big/127.jpg',
    detailImgSrc: 'public/image/product/detail/127.jpg',
    categoryId: 9,
    amount: '13,500',
    originalAmount: '',
    sale: 0,
  },
  '128': {
    id: 128,
    title: '매거진F No.02 cheese',
    productImgSrc: 'public/image/product/big/128.jpg',
    detailImgSrc: 'public/image/product/detail/128.jpg',
    categoryId: 3,
    amount: '13,500',
    originalAmount: '15,000',
    sale: 10,
  },
  '129': {
    id: 129,
    title: '세븐일레븐X배민. 주문하신 커피 5종',
    productImgSrc: 'public/image/product/big/129.jpg',
    detailImgSrc: 'public/image/product/detail/129.jpg',
    categoryId: 9,
    amount: '13,500',
    originalAmount: '',
    sale: 0,
  },
  '130': {
    id: 130,
    title: '제 2회 배민 치믈리에 자격시험 (7/5)',
    productImgSrc: 'public/image/product/big/130.jpg',
    detailImgSrc: 'public/image/product/detail/130.jpg',
    categoryId: 10,
    amount: '5,000',
    originalAmount: '',
    sale: 0,
  },
  '131': {
    id: 131,
    title: '제 2회 배민 치믈리에 자격시험 (7/10)',
    productImgSrc: 'public/image/product/big/131.jpg',
    detailImgSrc: 'public/image/product/detail/131.jpg',
    categoryId: 10,
    amount: '5,000',
    originalAmount: '',
    sale: 0,
  },
  '132': {
    id: 132,
    title: '제 2회 배민 치믈리에 자격시험 (7/12)',
    productImgSrc: 'public/image/product/big/132.jpg',
    detailImgSrc: 'public/image/product/detail/132.jpg',
    categoryId: 10,
    amount: '5,000',
    originalAmount: '',
    sale: 0,
  },
  '133': {
    id: 133,
    title: '[EVENT] 아, 시원하다~',
    productImgSrc: 'public/image/product/big/133.jpg',
    detailImgSrc: 'public/image/product/detail/133.jpg',
    categoryId: 10,
    amount: '5,000',
    originalAmount: '',
    sale: 0,
  },
  '134': {
    id: 134,
    title: '치슐랭가이드',
    productImgSrc: 'public/image/product/big/134.jpg',
    detailImgSrc: 'public/image/product/detail/134.jpg',
    categoryId: 3,
    amount: '11,520',
    originalAmount: '12,800',
    sale: 10,
  },
  '135': {
    id: 135,
    title: '매거진F No.03 chicken',
    productImgSrc: 'public/image/product/big/135.jpg',
    detailImgSrc: 'public/image/product/detail/135.jpg',
    categoryId: 3,
    amount: '13,500',
    originalAmount: '15,000',
    sale: 10,
  },
  '136': {
    id: 136,
    title: '씻고자자 목욕선물세트',
    productImgSrc: 'public/image/product/big/136.jpg',
    detailImgSrc: 'public/image/product/detail/136.jpg',
    categoryId: 9,
    amount: '13,500',
    originalAmount: '',
    sale: 0,
  },
  '137': {
    id: 137,
    title: '효자손. 혼자서도 잘해요',
    productImgSrc: 'public/image/product/big/137.jpg',
    detailImgSrc: 'public/image/product/detail/137.jpg',
    categoryId: 8,
    amount: '12,900',
    originalAmount: '',
    sale: 0,
  },
  '138': {
    id: 138,
    title: '추석연휴 배송공지',
    productImgSrc: 'public/image/product/big/138.jpg',
    detailImgSrc: 'public/image/product/detail/138.jpg',
    categoryId: 10,
    amount: '12,900',
    originalAmount: '',
    sale: 0,
  },
  '139': {
    id: 139,
    title: '매거진F No.04 Tomato',
    productImgSrc: 'public/image/product/big/139.jpg',
    detailImgSrc: 'public/image/product/detail/139.jpg',
    categoryId: 3,
    amount: '13,500',
    originalAmount: '15,000',
    sale: 10,
  },
  '140': {
    id: 140,
    title: '무릎담요. 외롭지 않아 단지 추울 뿐',
    productImgSrc: 'public/image/product/big/140.jpg',
    detailImgSrc: 'public/image/product/detail/140.jpg',
    categoryId: 2,
    amount: '13,500',
    originalAmount: '',
    sale: 0,
  },
  '141': {
    id: 141,
    title: '더부스X배달의민족. 치믈리에일',
    productImgSrc: 'public/image/product/big/141.jpg',
    detailImgSrc: 'public/image/product/detail/141.jpg',
    categoryId: 9,
    amount: '13,500',
    originalAmount: '',
    sale: 0,
  },
  '142': {
    id: 142,
    title: '컴퓨터싸인펜. 오늘이 전설이 될 것이다',
    productImgSrc: 'public/image/product/big/142.jpg',
    detailImgSrc: 'public/image/product/detail/142.jpg',
    categoryId: 1,
    amount: '1,000',
    originalAmount: '',
    sale: 0,
  },
  '143': {
    id: 143,
    title: '더부스X배달의민족. 치믈리에일 맥주잔',
    productImgSrc: 'public/image/product/big/143.jpg',
    detailImgSrc: 'public/image/product/detail/143.jpg',
    categoryId: 9,
    amount: '1,000',
    originalAmount: '',
    sale: 0,
  },
  '144': {
    id: 144,
    title: '2019 일력. 여기여기 붙어라',
    productImgSrc: 'public/image/product/big/144.jpg',
    detailImgSrc: 'public/image/product/detail/144.jpg',
    categoryId: 10,
    amount: '1,000',
    originalAmount: '',
    sale: 0,
  },
  '145': {
    id: 145,
    title: '매거진F No.05 Rice',
    productImgSrc: 'public/image/product/big/145.jpg',
    detailImgSrc: 'public/image/product/detail/145.jpg',
    categoryId: 3,
    amount: '13,500',
    originalAmount: '15,000',
    sale: 10,
  },
  '146': {
    id: 146,
    title: '이게 다 넛때문이야. 선물세트',
    productImgSrc: 'public/image/product/big/146.jpg',
    detailImgSrc: 'public/image/product/detail/146.jpg',
    categoryId: 9,
    amount: '13,500',
    originalAmount: '',
    sale: 0,
  },
  '147': {
    id: 147,
    title: '연말 배송공지',
    productImgSrc: 'public/image/product/big/147.jpg',
    detailImgSrc: 'public/image/product/detail/147.jpg',
    categoryId: 10,
    amount: '13,500',
    originalAmount: '',
    sale: 0,
  },
  '148': {
    id: 148,
    title: '장기하와 얼굴들. 노트 세트 (5개입)',
    productImgSrc: 'public/image/product/big/148.jpg',
    detailImgSrc: 'public/image/product/detail/148.jpg',
    categoryId: 9,
    amount: '12,000',
    originalAmount: '',
    sale: 0,
  },
  '149': {
    id: 149,
    title: '돈봉투. 새해 복 (화이트/블랙)',
    productImgSrc: 'public/image/product/big/149.jpg',
    detailImgSrc: 'public/image/product/detail/149.jpg',
    categoryId: 9,
    amount: '12,000',
    originalAmount: '',
    sale: 0,
  },
  '150': {
    id: 150,
    title: '장기하와 얼굴들. 마스킹테이프 세트',
    productImgSrc: 'public/image/product/big/150.jpg',
    detailImgSrc: 'public/image/product/detail/150.jpg',
    categoryId: 9,
    amount: '5,500',
    originalAmount: '',
    sale: 0,
  },
  '151': {
    id: 151,
    title: '난방비 걱정없는. 핫팩 세트',
    productImgSrc: 'public/image/product/big/151.jpg',
    detailImgSrc: 'public/image/product/detail/151.jpg',
    categoryId: 9,
    amount: '5,500',
    originalAmount: '',
    sale: 0,
  },
  '152': {
    id: 152,
    title: '볼펜세트. 어머 펜이에요~',
    productImgSrc: 'public/image/product/big/152.jpg',
    detailImgSrc: 'public/image/product/detail/152.jpg',
    categoryId: 8,
    amount: '3,500',
    originalAmount: '',
    sale: 0,
  },
  '153': {
    id: 153,
    title: '설날 배송공지 ',
    productImgSrc: 'public/image/product/big/153.jpg',
    detailImgSrc: 'public/image/product/detail/153.jpg',
    categoryId: 10,
    amount: '3,500',
    originalAmount: '',
    sale: 0,
  },
  '154': {
    id: 154,
    title: '매거진F No.06 Chocolate',
    productImgSrc: 'public/image/product/big/154.jpg',
    detailImgSrc: 'public/image/product/detail/154.jpg',
    categoryId: 3,
    amount: '13,500',
    originalAmount: '15,000',
    sale: 10,
  },
  '155': {
    id: 155,
    title: '누가 나 좀 말려줘요. 수건세트',
    productImgSrc: 'public/image/product/big/155.jpg',
    detailImgSrc: 'public/image/product/detail/155.jpg',
    categoryId: 8,
    amount: '25,000',
    originalAmount: '',
    sale: 0,
  },
  '156': {
    id: 156,
    title: '배달이 팝업북. 버거나라 삼남매',
    productImgSrc: 'public/image/product/big/156.jpg',
    detailImgSrc: 'public/image/product/detail/156.jpg',
    categoryId: 9,
    amount: '25,000',
    originalAmount: '',
    sale: 0,
  },
  '157': {
    id: 157,
    title: '1만명 기념. 깜짝 이벤트',
    productImgSrc: 'public/image/product/big/157.jpg',
    detailImgSrc: 'public/image/product/detail/157.jpg',
    categoryId: 10,
    amount: '10,000',
    originalAmount: '',
    sale: 0,
  },
  '158': {
    id: 158,
    title: '서디페. 마스킹 테이프',
    productImgSrc: 'public/image/product/big/158.jpg',
    detailImgSrc: 'public/image/product/detail/158.jpg',
    categoryId: 1,
    amount: '6,000',
    originalAmount: '',
    sale: 0,
  },
  '159': {
    id: 159,
    title: '매거진F No.07 Vinegar',
    productImgSrc: 'public/image/product/big/159.jpg',
    detailImgSrc: 'public/image/product/detail/159.jpg',
    categoryId: 3,
    amount: '13,500',
    originalAmount: '15,000',
    sale: 10,
  },
  '160': {
    id: 160,
    title: '오뚜기X배달의민족. 사골곰탕',
    productImgSrc: 'public/image/product/big/160.jpg',
    detailImgSrc: 'public/image/product/detail/160.jpg',
    categoryId: 9,
    amount: '13,500',
    originalAmount: '',
    sale: 0,
  },
  '161': {
    id: 161,
    title: '매거진F No.08 Honey',
    productImgSrc: 'public/image/product/big/161.jpg',
    detailImgSrc: 'public/image/product/detail/161.jpg',
    categoryId: 3,
    amount: '13,500',
    originalAmount: '15,000',
    sale: 10,
  },
  '162': {
    id: 162,
    title: '물놀이 세트',
    productImgSrc: 'public/image/product/big/162.jpg',
    detailImgSrc: 'public/image/product/detail/162.jpg',
    categoryId: 10,
    amount: '15,000',
    originalAmount: '32,500',
    sale: 53,
  },
  '163': {
    id: 163,
    title: '반반휴지. 물반휴지반',
    productImgSrc: 'public/image/product/big/163.jpg',
    detailImgSrc: 'public/image/product/detail/163.jpg',
    categoryId: 2,
    amount: '1,500',
    originalAmount: '',
    sale: 0,
  },
  '164': {
    id: 164,
    title: 'ㅋㅋ슬리퍼',
    productImgSrc: 'public/image/product/big/164.jpg',
    detailImgSrc: 'public/image/product/detail/164.jpg',
    categoryId: 10,
    amount: '1,500',
    originalAmount: '',
    sale: 0,
  },
  '165': {
    id: 165,
    title: 'ㅋㅋ반팔티셔츠 화이트',
    productImgSrc: 'public/image/product/big/165.jpg',
    detailImgSrc: 'public/image/product/detail/165.jpg',
    categoryId: 5,
    amount: '25,000',
    originalAmount: '',
    sale: 0,
  },
  '166': {
    id: 166,
    title: 'ㅋㅋ안 보이는 양말',
    productImgSrc: 'public/image/product/big/166.jpg',
    detailImgSrc: 'public/image/product/detail/166.jpg',
    categoryId: 10,
    amount: '4,000',
    originalAmount: '',
    sale: 0,
  },
  '167': {
    id: 167,
    title: 'ㅋㅋ캐리어벨트',
    productImgSrc: 'public/image/product/big/167.jpg',
    detailImgSrc: 'public/image/product/detail/167.jpg',
    categoryId: 5,
    amount: '14,000',
    originalAmount: '',
    sale: 0,
  },
  '168': {
    id: 168,
    title: 'ㅋㅋ폰케이스',
    productImgSrc: 'public/image/product/big/168.jpg',
    detailImgSrc: 'public/image/product/detail/168.jpg',
    categoryId: 5,
    amount: '16,000',
    originalAmount: '',
    sale: 0,
  },
  '169': {
    id: 169,
    title: 'ㅋㅋ안 보이는 양말 5개 세트',
    productImgSrc: 'public/image/product/big/169.jpg',
    detailImgSrc: 'public/image/product/detail/169.jpg',
    categoryId: 10,
    amount: '19,000',
    originalAmount: '20,000',
    sale: 5,
  },
  '170': {
    id: 170,
    title: '매거진F 아트 북',
    productImgSrc: 'public/image/product/big/170.jpg',
    detailImgSrc: 'public/image/product/detail/170.jpg',
    categoryId: 3,
    amount: '42,300',
    originalAmount: '47,000',
    sale: 10,
  },
  '171': {
    id: 171,
    title: '매거진F No.09 Curry',
    productImgSrc: 'public/image/product/big/171.jpg',
    detailImgSrc: 'public/image/product/detail/171.jpg',
    categoryId: 3,
    amount: '13,500',
    originalAmount: '15,000',
    sale: 10,
  },
  '172': {
    id: 172,
    title: '일기장. 쓰고 자자',
    productImgSrc: 'public/image/product/big/172.jpg',
    detailImgSrc: 'public/image/product/detail/172.jpg',
    categoryId: 1,
    amount: '3,000',
    originalAmount: '',
    sale: 0,
  },
  '173': {
    id: 173,
    title: '세븐일레븐X배달의민족. 눈물나는젤리',
    productImgSrc: 'public/image/product/big/173.jpg',
    detailImgSrc: 'public/image/product/detail/173.jpg',
    categoryId: 9,
    amount: '3,000',
    originalAmount: '',
    sale: 0,
  },
  '174': {
    id: 174,
    title: '매거진F No.10 Berry',
    productImgSrc: 'public/image/product/big/174.jpg',
    detailImgSrc: 'public/image/product/detail/174.jpg',
    categoryId: 3,
    amount: '13,500',
    originalAmount: '15,000',
    sale: 10,
  },
  '175': {
    id: 175,
    title: '돈봉투. 축하',
    productImgSrc: 'public/image/product/big/175.jpg',
    detailImgSrc: 'public/image/product/detail/175.jpg',
    categoryId: 1,
    amount: '2,500',
    originalAmount: '',
    sale: 0,
  },
  '176': {
    id: 176,
    title: '돈봉투. 용돈',
    productImgSrc: 'public/image/product/big/176.jpg',
    detailImgSrc: 'public/image/product/detail/176.jpg',
    categoryId: 1,
    amount: '2,500',
    originalAmount: '',
    sale: 0,
  },
  '177': {
    id: 177,
    title: '돈봉투. 효도',
    productImgSrc: 'public/image/product/big/177.jpg',
    detailImgSrc: 'public/image/product/detail/177.jpg',
    categoryId: 1,
    amount: '2,500',
    originalAmount: '',
    sale: 0,
  },
  '178': {
    id: 178,
    title: '돈봉투. 사랑',
    productImgSrc: 'public/image/product/big/178.jpg',
    detailImgSrc: 'public/image/product/detail/178.jpg',
    categoryId: 1,
    amount: '2,500',
    originalAmount: '',
    sale: 0,
  },
  '179': {
    id: 179,
    title: '돈봉투. 골드에디션 효도',
    productImgSrc: 'public/image/product/big/179.jpg',
    detailImgSrc: 'public/image/product/detail/179.jpg',
    categoryId: 1,
    amount: '3,500',
    originalAmount: '',
    sale: 0,
  },
  '180': {
    id: 180,
    title: '스티커. 대한민국',
    productImgSrc: 'public/image/product/big/180.jpg',
    detailImgSrc: 'public/image/product/detail/180.jpg',
    categoryId: 10,
    amount: '1,500',
    originalAmount: '',
    sale: 0,
  },
  '181': {
    id: 181,
    title: '스티커. 봉인해제',
    productImgSrc: 'public/image/product/big/181.jpg',
    detailImgSrc: 'public/image/product/detail/181.jpg',
    categoryId: 1,
    amount: '1,500',
    originalAmount: '',
    sale: 0,
  },
  '182': {
    id: 182,
    title: '스티커. 비상구',
    productImgSrc: 'public/image/product/big/182.jpg',
    detailImgSrc: 'public/image/product/detail/182.jpg',
    categoryId: 1,
    amount: '1,500',
    originalAmount: '',
    sale: 0,
  },
  '183': {
    id: 183,
    title: '스티커. 접근금지',
    productImgSrc: 'public/image/product/big/183.jpg',
    detailImgSrc: 'public/image/product/detail/183.jpg',
    categoryId: 1,
    amount: '1,500',
    originalAmount: '',
    sale: 0,
  },
  '184': {
    id: 184,
    title: '스티커. 지켜보고있다',
    productImgSrc: 'public/image/product/big/184.jpg',
    detailImgSrc: 'public/image/product/detail/184.jpg',
    categoryId: 1,
    amount: '1,500',
    originalAmount: '',
    sale: 0,
  },
  '185': {
    id: 185,
    title: '스티커. 흠집보호',
    productImgSrc: 'public/image/product/big/185.jpg',
    detailImgSrc: 'public/image/product/detail/185.jpg',
    categoryId: 1,
    amount: '1,500',
    originalAmount: '',
    sale: 0,
  },
  '186': {
    id: 186,
    title: '쇼핑백. 축복',
    productImgSrc: 'public/image/product/big/186.jpg',
    detailImgSrc: 'public/image/product/detail/186.jpg',
    categoryId: 10,
    amount: '1,500',
    originalAmount: '',
    sale: 0,
  },
  '187': {
    id: 187,
    title: '박스테이프. 60초 후에',
    productImgSrc: 'public/image/product/big/187.jpg',
    detailImgSrc: 'public/image/product/detail/187.jpg',
    categoryId: 1,
    amount: '4,500',
    originalAmount: '',
    sale: 0,
  },
  '188': {
    id: 188,
    title: '레터링시트지. 큰일을 해결하면',
    productImgSrc: 'public/image/product/big/188.jpg',
    detailImgSrc: 'public/image/product/detail/188.jpg',
    categoryId: 2,
    amount: '4,000',
    originalAmount: '',
    sale: 0,
  },
  '189': {
    id: 189,
    title: '레터링시트지. 오늘이 전설이 될 것이다',
    productImgSrc: 'public/image/product/big/189.jpg',
    detailImgSrc: 'public/image/product/detail/189.jpg',
    categoryId: 2,
    amount: '4,000',
    originalAmount: '',
    sale: 0,
  },
  '190': {
    id: 190,
    title: '레터링시트지. 누군가의 꿈이 되는',
    productImgSrc: 'public/image/product/big/190.jpg',
    detailImgSrc: 'public/image/product/detail/190.jpg',
    categoryId: 2,
    amount: '4,000',
    originalAmount: '',
    sale: 0,
  },
  '191': {
    id: 191,
    title: '레터링시트지. 가슴은 뜨겁게',
    productImgSrc: 'public/image/product/big/191.jpg',
    detailImgSrc: 'public/image/product/detail/191.jpg',
    categoryId: 2,
    amount: '4,000',
    originalAmount: '',
    sale: 0,
  },
  '192': {
    id: 192,
    title: '레터링시트지. 우린 아직 젊기에',
    productImgSrc: 'public/image/product/big/192.jpg',
    detailImgSrc: 'public/image/product/detail/192.jpg',
    categoryId: 2,
    amount: '4,000',
    originalAmount: '',
    sale: 0,
  },
  '193': {
    id: 193,
    title: '레터링시트지. 휴가에는 사유가 없습니다',
    productImgSrc: 'public/image/product/big/193.jpg',
    detailImgSrc: 'public/image/product/detail/193.jpg',
    categoryId: 2,
    amount: '4,000',
    originalAmount: '',
    sale: 0,
  },
  '194': {
    id: 194,
    title: '숫자픽 세트',
    productImgSrc: 'public/image/product/big/194.jpg',
    detailImgSrc: 'public/image/product/detail/194.jpg',
    categoryId: 2,
    amount: '2,500',
    originalAmount: '',
    sale: 0,
  },
  '195': {
    id: 195,
    title: '생활공감 노트. 우유부단',
    productImgSrc: 'public/image/product/big/195.jpg',
    detailImgSrc: 'public/image/product/detail/195.jpg',
    categoryId: 1,
    amount: '2,500',
    originalAmount: '',
    sale: 0,
  },
  '196': {
    id: 196,
    title: '생활공감 노트. 따지고보면',
    productImgSrc: 'public/image/product/big/196.jpg',
    detailImgSrc: 'public/image/product/detail/196.jpg',
    categoryId: 1,
    amount: '2,500',
    originalAmount: '',
    sale: 0,
  },
  '197': {
    id: 197,
    title: '생활공감 노트. 아 저는 뭐',
    productImgSrc: 'public/image/product/big/197.jpg',
    detailImgSrc: 'public/image/product/detail/197.jpg',
    categoryId: 1,
    amount: '2,500',
    originalAmount: '',
    sale: 0,
  },
  '198': {
    id: 198,
    title: '넛때문이야. 호두',
    productImgSrc: 'public/image/product/big/198.jpg',
    detailImgSrc: 'public/image/product/detail/198.jpg',
    categoryId: 9,
    amount: '2,500',
    originalAmount: '',
    sale: 0,
  },
  '199': {
    id: 199,
    title: '넛때문이야. 캐슈넛',
    productImgSrc: 'public/image/product/big/199.jpg',
    detailImgSrc: 'public/image/product/detail/199.jpg',
    categoryId: 9,
    amount: '2,500',
    originalAmount: '',
    sale: 0,
  },
  '200': {
    id: 200,
    title: '기름종이 있어?',
    productImgSrc: 'public/image/product/big/200.jpg',
    detailImgSrc: 'public/image/product/detail/200.jpg',
    categoryId: 2,
    amount: '2,700',
    originalAmount: '',
    sale: 0,
  },
  '201': {
    id: 201,
    title: '머리끈 있어?',
    productImgSrc: 'public/image/product/big/201.jpg',
    detailImgSrc: 'public/image/product/detail/201.jpg',
    categoryId: 2,
    amount: '1,500',
    originalAmount: '',
    sale: 0,
  },
  '202': {
    id: 202,
    title: '스탠드그립. 뾱',
    productImgSrc: 'public/image/product/big/202.jpg',
    detailImgSrc: 'public/image/product/detail/202.jpg',
    categoryId: 2,
    amount: '8,900',
    originalAmount: '',
    sale: 0,
  },
  '203': {
    id: 203,
    title: '실핀 있어?',
    productImgSrc: 'public/image/product/big/203.jpg',
    detailImgSrc: 'public/image/product/detail/203.jpg',
    categoryId: 2,
    amount: '2,300',
    originalAmount: '',
    sale: 0,
  },
  '204': {
    id: 204,
    title: '스탠드그립. 캬',
    productImgSrc: 'public/image/product/big/204.jpg',
    detailImgSrc: 'public/image/product/detail/204.jpg',
    categoryId: 2,
    amount: '8,900',
    originalAmount: '',
    sale: 0,
  },
  '205': {
    id: 205,
    title: 'ㅋㅋ스탠드그립',
    productImgSrc: 'public/image/product/big/205.jpg',
    detailImgSrc: 'public/image/product/detail/205.jpg',
    categoryId: 5,
    amount: '8,900',
    originalAmount: '',
    sale: 0,
  },
  '206': {
    id: 206,
    title: '2020 일력. 오늘이 전설이 될 것이다',
    productImgSrc: 'public/image/product/big/206.jpg',
    detailImgSrc: 'public/image/product/detail/206.jpg',
    categoryId: 10,
    amount: '8,900',
    originalAmount: '',
    sale: 0,
  },
  '207': {
    id: 207,
    title: '2020 다이어리. 오늘이 전설이 될 것이다',
    productImgSrc: 'public/image/product/big/207.jpg',
    detailImgSrc: 'public/image/product/detail/207.jpg',
    categoryId: 10,
    amount: '8,900',
    originalAmount: '',
    sale: 0,
  },
  '208': {
    id: 208,
    title: 'ㅋㅋ젤리폰케이스+스티커 세트',
    productImgSrc: 'public/image/product/big/208.jpg',
    detailImgSrc: 'public/image/product/detail/208.jpg',
    categoryId: 5,
    amount: '16,000',
    originalAmount: '',
    sale: 0,
  },
  '209': {
    id: 209,
    title: '매거진F No.11 Bean',
    productImgSrc: 'public/image/product/big/209.jpg',
    detailImgSrc: 'public/image/product/detail/209.jpg',
    categoryId: 3,
    amount: '13,500',
    originalAmount: '15,000',
    sale: 10,
  },
  '210': {
    id: 210,
    title: 'ㅋㅋ슬리퍼 블랙',
    productImgSrc: 'public/image/product/big/210.jpg',
    detailImgSrc: 'public/image/product/detail/210.jpg',
    categoryId: 5,
    amount: '21,000',
    originalAmount: '',
    sale: 0,
  },
  '211': {
    id: 211,
    title: 'ㅋㅋ슬리퍼 화이트',
    productImgSrc: 'public/image/product/big/211.jpg',
    detailImgSrc: 'public/image/product/detail/211.jpg',
    categoryId: 5,
    amount: '21,000',
    originalAmount: '',
    sale: 0,
  },
  '212': {
    id: 212,
    title: '헤어롤 있어?',
    productImgSrc: 'public/image/product/big/212.jpg',
    detailImgSrc: 'public/image/product/detail/212.jpg',
    categoryId: 2,
    amount: '1,200',
    originalAmount: '',
    sale: 0,
  },
  '213': {
    id: 213,
    title: '빗 있어?',
    productImgSrc: 'public/image/product/big/213.jpg',
    detailImgSrc: 'public/image/product/detail/213.jpg',
    categoryId: 2,
    amount: '1,500',
    originalAmount: '',
    sale: 0,
  },
  '214': {
    id: 214,
    title: '거울 있어?',
    productImgSrc: 'public/image/product/big/214.jpg',
    detailImgSrc: 'public/image/product/detail/214.jpg',
    categoryId: 2,
    amount: '4,500',
    originalAmount: '',
    sale: 0,
  },
  '215': {
    id: 215,
    title: '0원 박스',
    productImgSrc: 'public/image/product/big/215.jpg',
    detailImgSrc: 'public/image/product/detail/215.jpg',
    categoryId: 10,
    amount: '0',
    originalAmount: '',
    sale: 0,
  },
  '216': {
    id: 216,
    title: '미니언즈X배달의민족. 혼밥식기세트',
    productImgSrc: 'public/image/product/big/216.jpg',
    detailImgSrc: 'public/image/product/detail/216.jpg',
    categoryId: 9,
    amount: '0',
    originalAmount: '',
    sale: 0,
  },
  '217': {
    id: 217,
    title: '일기장 세트. 쓰고 자자',
    productImgSrc: 'public/image/product/big/217.jpg',
    detailImgSrc: 'public/image/product/detail/217.jpg',
    categoryId: 1,
    amount: '0',
    originalAmount: '',
    sale: 0,
  },
  '218': {
    id: 218,
    title: '메모잇. 진짜 까먹지 말자',
    productImgSrc: 'public/image/product/big/218.jpg',
    detailImgSrc: 'public/image/product/detail/218.jpg',
    categoryId: 1,
    amount: '1,500',
    originalAmount: '',
    sale: 0,
  },
  '219': {
    id: 219,
    title: '잘나가요 세트',
    productImgSrc: 'public/image/product/big/219.jpg',
    detailImgSrc: 'public/image/product/detail/219.jpg',
    categoryId: 8,
    amount: '15,000',
    originalAmount: '',
    sale: 0,
  },
  '220': {
    id: 220,
    title: '파일. 아 보람차다',
    productImgSrc: 'public/image/product/big/220.jpg',
    detailImgSrc: 'public/image/product/detail/220.jpg',
    categoryId: 1,
    amount: '1,500',
    originalAmount: '',
    sale: 0,
  },
  '221': {
    id: 221,
    title: '파일. 까먹지 말자',
    productImgSrc: 'public/image/product/big/221.jpg',
    detailImgSrc: 'public/image/product/detail/221.jpg',
    categoryId: 1,
    amount: '1,500',
    originalAmount: '',
    sale: 0,
  },
  '222': {
    id: 222,
    title: '파일. 선생님 감사해요',
    productImgSrc: 'public/image/product/big/222.jpg',
    detailImgSrc: 'public/image/product/detail/222.jpg',
    categoryId: 1,
    amount: '1,500',
    originalAmount: '',
    sale: 0,
  },
  '223': {
    id: 223,
    title: '쉿 비밀펜',
    productImgSrc: 'public/image/product/big/223.jpg',
    detailImgSrc: 'public/image/product/detail/223.jpg',
    categoryId: 1,
    amount: '2,500',
    originalAmount: '',
    sale: 0,
  },
  '224': {
    id: 224,
    title: '매거진F No.12 Kimchi',
    productImgSrc: 'public/image/product/big/224.jpg',
    detailImgSrc: 'public/image/product/detail/224.jpg',
    categoryId: 3,
    amount: '13,500',
    originalAmount: '15,000',
    sale: 10,
  },
  '225': {
    id: 225,
    title: '미니갑티슈. 티었슈?',
    productImgSrc: 'public/image/product/big/225.jpg',
    detailImgSrc: 'public/image/product/detail/225.jpg',
    categoryId: 2,
    amount: '2,200',
    originalAmount: '',
    sale: 0,
  },
  '226': {
    id: 226,
    title: '뱃지. 쌀국수',
    productImgSrc: 'public/image/product/big/226.jpg',
    detailImgSrc: 'public/image/product/detail/226.jpg',
    categoryId: 2,
    amount: '5,500',
    originalAmount: '',
    sale: 0,
  },
  '227': {
    id: 227,
    title: '뱃지. 떡볶이',
    productImgSrc: 'public/image/product/big/227.jpg',
    detailImgSrc: 'public/image/product/detail/227.jpg',
    categoryId: 2,
    amount: '5,500',
    originalAmount: '',
    sale: 0,
  },
  '228': {
    id: 228,
    title: '뱃지. 짜장면',
    productImgSrc: 'public/image/product/big/228.jpg',
    detailImgSrc: 'public/image/product/detail/228.jpg',
    categoryId: 2,
    amount: '5,500',
    originalAmount: '',
    sale: 0,
  },
  '229': {
    id: 229,
    title: '뱃지. 쌀밥',
    productImgSrc: 'public/image/product/big/229.jpg',
    detailImgSrc: 'public/image/product/detail/229.jpg',
    categoryId: 2,
    amount: '5,500',
    originalAmount: '',
    sale: 0,
  },
  '230': {
    id: 230,
    title: '뱃지. 햄버거',
    productImgSrc: 'public/image/product/big/230.jpg',
    detailImgSrc: 'public/image/product/detail/230.jpg',
    categoryId: 2,
    amount: '5,500',
    originalAmount: '',
    sale: 0,
  },
  '231': {
    id: 231,
    title: 'ㅋㅋ반팔티셔츠 블랙',
    productImgSrc: 'public/image/product/big/231.jpg',
    detailImgSrc: 'public/image/product/detail/231.jpg',
    categoryId: 5,
    amount: '25,000',
    originalAmount: '',
    sale: 0,
  },
  '232': {
    id: 232,
    title: '매거진F No.13 Clam',
    productImgSrc: 'public/image/product/big/232.jpg',
    detailImgSrc: 'public/image/product/detail/232.jpg',
    categoryId: 3,
    amount: '13,500',
    originalAmount: '15,000',
    sale: 10,
  },
  '233': {
    id: 233,
    title: '에코백. 난 너의 든든한 빽 (화이트)',
    productImgSrc: 'public/image/product/big/233.jpg',
    detailImgSrc: 'public/image/product/detail/233.jpg',
    categoryId: 2,
    amount: '15,000',
    originalAmount: '',
    sale: 0,
  },
  '234': {
    id: 234,
    title: '에코백. 난 너의 든든한 빽 (블랙)',
    productImgSrc: 'public/image/product/big/234.jpg',
    detailImgSrc: 'public/image/product/detail/234.jpg',
    categoryId: 2,
    amount: '15,000',
    originalAmount: '',
    sale: 0,
  },
  '235': {
    id: 235,
    title: '크로스에코백. 난 너의 든든한 빽 (화이트)',
    productImgSrc: 'public/image/product/big/235.jpg',
    detailImgSrc: 'public/image/product/detail/235.jpg',
    categoryId: 2,
    amount: '17,000',
    originalAmount: '',
    sale: 0,
  },
  '236': {
    id: 236,
    title: '크로스에코백. 난 너의 든든한 빽 (블랙)',
    productImgSrc: 'public/image/product/big/236.jpg',
    detailImgSrc: 'public/image/product/detail/236.jpg',
    categoryId: 2,
    amount: '17,000',
    originalAmount: '',
    sale: 0,
  },
  '237': {
    id: 237,
    title: 'ㅋㅋ웃기는 양말 (화이트)',
    productImgSrc: 'public/image/product/big/237.jpg',
    detailImgSrc: 'public/image/product/detail/237.jpg',
    categoryId: 5,
    amount: '5,500',
    originalAmount: '',
    sale: 0,
  },
  '238': {
    id: 238,
    title: 'ㅋㅋ웃기는 양말 (블랙)',
    productImgSrc: 'public/image/product/big/238.jpg',
    detailImgSrc: 'public/image/product/detail/238.jpg',
    categoryId: 5,
    amount: '5,500',
    originalAmount: '',
    sale: 0,
  },
  '239': {
    id: 239,
    title: 'ㅋㅋ한 줄 양말 (화이트)',
    productImgSrc: 'public/image/product/big/239.jpg',
    detailImgSrc: 'public/image/product/detail/239.jpg',
    categoryId: 5,
    amount: '5,500',
    originalAmount: '',
    sale: 0,
  },
  '240': {
    id: 240,
    title: 'ㅋㅋ한 줄 양말 (블랙)',
    productImgSrc: 'public/image/product/big/240.jpg',
    detailImgSrc: 'public/image/product/detail/240.jpg',
    categoryId: 5,
    amount: '5,500',
    originalAmount: '',
    sale: 0,
  },
  '241': {
    id: 241,
    title: 'ㅋㅋ안 보이는 양말 (화이트)',
    productImgSrc: 'public/image/product/big/241.jpg',
    detailImgSrc: 'public/image/product/detail/241.jpg',
    categoryId: 5,
    amount: '4,000',
    originalAmount: '',
    sale: 0,
  },
  '242': {
    id: 242,
    title: 'ㅋㅋ안 보이는 양말 (블랙)',
    productImgSrc: 'public/image/product/big/242.jpg',
    detailImgSrc: 'public/image/product/detail/242.jpg',
    categoryId: 5,
    amount: '4,000',
    originalAmount: '',
    sale: 0,
  },
  '243': {
    id: 243,
    title: '양말. 왼발오른발 (화이트)',
    productImgSrc: 'public/image/product/big/243.jpg',
    detailImgSrc: 'public/image/product/detail/243.jpg',
    categoryId: 2,
    amount: '5,500',
    originalAmount: '',
    sale: 0,
  },
  '244': {
    id: 244,
    title: '양말. 왼발오른발 (블랙)',
    productImgSrc: 'public/image/product/big/244.jpg',
    detailImgSrc: 'public/image/product/detail/244.jpg',
    categoryId: 2,
    amount: '5,500',
    originalAmount: '',
    sale: 0,
  },
  '245': {
    id: 245,
    title: 'ㅋㅋ골고루 양말 세트',
    productImgSrc: 'public/image/product/big/245.jpg',
    detailImgSrc: 'public/image/product/detail/245.jpg',
    categoryId: 8,
    amount: '26,000',
    originalAmount: '27,500',
    sale: 5,
  },
  '246': {
    id: 246,
    title: 'ㅋㅋ안 보이는 양말 세트',
    productImgSrc: 'public/image/product/big/246.jpg',
    detailImgSrc: 'public/image/product/detail/246.jpg',
    categoryId: 8,
    amount: '19,000',
    originalAmount: '20,000',
    sale: 5,
  },
  '247': {
    id: 247,
    title: '왼발오른발 양말 세트',
    productImgSrc: 'public/image/product/big/247.jpg',
    detailImgSrc: 'public/image/product/detail/247.jpg',
    categoryId: 8,
    amount: '26,000',
    originalAmount: '27,500',
    sale: 5,
  },
  '248': {
    id: 248,
    title: '미니갑티슈 세트. 티었슈?',
    productImgSrc: 'public/image/product/big/248.jpg',
    detailImgSrc: 'public/image/product/detail/248.jpg',
    categoryId: 8,
    amount: '8,000',
    originalAmount: '8,800',
    sale: 9,
  },
  '249': {
    id: 249,
    title: '작은 쇼핑백. 축복',
    productImgSrc: 'public/image/product/big/249.jpg',
    detailImgSrc: 'public/image/product/detail/249.jpg',
    categoryId: 1,
    amount: '1,800',
    originalAmount: '',
    sale: 0,
  },
  '250': {
    id: 250,
    title: '큰 쇼핑백. 뭘 이런걸 다',
    productImgSrc: 'public/image/product/big/250.jpg',
    detailImgSrc: 'public/image/product/detail/250.jpg',
    categoryId: 1,
    amount: '2,300',
    originalAmount: '',
    sale: 0,
  },
  '251': {
    id: 251,
    title: '생활공감 에코백. 따지고 보면',
    productImgSrc: 'public/image/product/big/251.jpg',
    detailImgSrc: 'public/image/product/detail/251.jpg',
    categoryId: 2,
    amount: '15,000',
    originalAmount: '',
    sale: 0,
  },
  '252': {
    id: 252,
    title: '생활공감 에코백. 아 저는 뭐',
    productImgSrc: 'public/image/product/big/252.jpg',
    detailImgSrc: 'public/image/product/detail/252.jpg',
    categoryId: 2,
    amount: '15,000',
    originalAmount: '',
    sale: 0,
  },
  '253': {
    id: 253,
    title: '생활공감 에코백. 우유부단',
    productImgSrc: 'public/image/product/big/253.jpg',
    detailImgSrc: 'public/image/product/detail/253.jpg',
    categoryId: 2,
    amount: '15,000',
    originalAmount: '',
    sale: 0,
  },
  '254': {
    id: 254,
    title: '피규어. 독고배달이',
    productImgSrc: 'public/image/product/big/254.jpg',
    detailImgSrc: 'public/image/product/detail/254.jpg',
    categoryId: 7,
    amount: '15,000',
    originalAmount: '',
    sale: 0,
  },
  '255': {
    id: 255,
    title: '피규어세트. 배달이친구들 5종',
    productImgSrc: 'public/image/product/big/255.jpg',
    detailImgSrc: 'public/image/product/detail/255.jpg',
    categoryId: 10,
    amount: '13,000',
    originalAmount: '15,000',
    sale: 13,
  },
  '256': {
    id: 256,
    title: '피규어. 냥이배달이',
    productImgSrc: 'public/image/product/big/256.jpg',
    detailImgSrc: 'public/image/product/detail/256.jpg',
    categoryId: 7,
    amount: '3,000',
    originalAmount: '',
    sale: 0,
  },
  '257': {
    id: 257,
    title: '피규어. 메이배달이',
    productImgSrc: 'public/image/product/big/257.jpg',
    detailImgSrc: 'public/image/product/detail/257.jpg',
    categoryId: 7,
    amount: '3,000',
    originalAmount: '',
    sale: 0,
  },
  '258': {
    id: 258,
    title: '피규어. 엉클배달이',
    productImgSrc: 'public/image/product/big/258.jpg',
    detailImgSrc: 'public/image/product/detail/258.jpg',
    categoryId: 7,
    amount: '3,000',
    originalAmount: '',
    sale: 0,
  },
  '259': {
    id: 259,
    title: '피규어. 왕배달이',
    productImgSrc: 'public/image/product/big/259.jpg',
    detailImgSrc: 'public/image/product/detail/259.jpg',
    categoryId: 7,
    amount: '3,000',
    originalAmount: '',
    sale: 0,
  },
  '260': {
    id: 260,
    title: '포스터. 독고배달이',
    productImgSrc: 'public/image/product/big/260.jpg',
    detailImgSrc: 'public/image/product/detail/260.jpg',
    categoryId: 7,
    amount: '2,000',
    originalAmount: '',
    sale: 0,
  },
  '261': {
    id: 261,
    title: '포스터. 냥이배달이',
    productImgSrc: 'public/image/product/big/261.jpg',
    detailImgSrc: 'public/image/product/detail/261.jpg',
    categoryId: 7,
    amount: '2,000',
    originalAmount: '',
    sale: 0,
  },
  '262': {
    id: 262,
    title: '포스터. 메이배달이',
    productImgSrc: 'public/image/product/big/262.jpg',
    detailImgSrc: 'public/image/product/detail/262.jpg',
    categoryId: 7,
    amount: '2,000',
    originalAmount: '',
    sale: 0,
  },
  '263': {
    id: 263,
    title: '포스터. 봉다리배달이',
    productImgSrc: 'public/image/product/big/263.jpg',
    detailImgSrc: 'public/image/product/detail/263.jpg',
    categoryId: 7,
    amount: '2,000',
    originalAmount: '',
    sale: 0,
  },
  '264': {
    id: 264,
    title: '포스터. 왕배달이',
    productImgSrc: 'public/image/product/big/264.jpg',
    detailImgSrc: 'public/image/product/detail/264.jpg',
    categoryId: 7,
    amount: '2,000',
    originalAmount: '',
    sale: 0,
  },
  '265': {
    id: 265,
    title: '0원 세트',
    productImgSrc: 'public/image/product/big/265.jpg',
    detailImgSrc: 'public/image/product/detail/265.jpg',
    categoryId: 10,
    amount: '0',
    originalAmount: '33,900',
    sale: 100,
  },
  '266': {
    id: 266,
    title: '매거진F 파운드:',
    productImgSrc: 'public/image/product/big/266.jpg',
    detailImgSrc: 'public/image/product/detail/266.jpg',
    categoryId: 3,
    amount: '16,200',
    originalAmount: '18,000',
    sale: 10,
  },
  '267': {
    id: 267,
    title: '종이로 만든 박스테이프. 60초 후에',
    productImgSrc: 'public/image/product/big/267.jpg',
    detailImgSrc: 'public/image/product/detail/267.jpg',
    categoryId: 4,
    amount: '4,500',
    originalAmount: '',
    sale: 0,
  },
  '268': {
    id: 268,
    title: '종이로 만든 박스테이프. 두근두근',
    productImgSrc: 'public/image/product/big/268.jpg',
    detailImgSrc: 'public/image/product/detail/268.jpg',
    categoryId: 4,
    amount: '4,500',
    originalAmount: '',
    sale: 0,
  },
  '269': {
    id: 269,
    title: '자투리 비누. 예쁘지는 않지만 사랑스러워',
    productImgSrc: 'public/image/product/big/269.jpg',
    detailImgSrc: 'public/image/product/detail/269.jpg',
    categoryId: 9,
    amount: '4,500',
    originalAmount: '',
    sale: 0,
  },
  '270': {
    id: 270,
    title: '을지로 연필. 사각사각',
    productImgSrc: 'public/image/product/big/270.jpg',
    detailImgSrc: 'public/image/product/detail/270.jpg',
    categoryId: 6,
    amount: '2,000',
    originalAmount: '',
    sale: 0,
  },
  '271': {
    id: 271,
    title: '을지로 일회용캬메라. 잘 나왔다',
    productImgSrc: 'public/image/product/big/271.jpg',
    detailImgSrc: 'public/image/product/detail/271.jpg',
    categoryId: 6,
    amount: '2,000',
    originalAmount: '',
    sale: 0,
  },
  '272': {
    id: 272,
    title: '을지로 목장갑. 위잉 뚝딱',
    productImgSrc: 'public/image/product/big/272.jpg',
    detailImgSrc: 'public/image/product/detail/272.jpg',
    categoryId: 6,
    amount: '6,000',
    originalAmount: '',
    sale: 0,
  },
  '273': {
    id: 273,
    title: '키크니. 별일 없이 산다 (특별 패키지)',
    productImgSrc: 'public/image/product/big/273.jpg',
    detailImgSrc: 'public/image/product/detail/273.jpg',
    categoryId: 3,
    amount: '26,000',
    originalAmount: '',
    sale: 0,
  },
  '274': {
    id: 274,
    title: '을지로 마스킹테이프. 십메다 줄자',
    productImgSrc: 'public/image/product/big/274.jpg',
    detailImgSrc: 'public/image/product/detail/274.jpg',
    categoryId: 6,
    amount: '4,500',
    originalAmount: '',
    sale: 0,
  },
  '275': {
    id: 275,
    title: '을지로에서 만든 뱃지. 고양이',
    productImgSrc: 'public/image/product/big/275.jpg',
    detailImgSrc: 'public/image/product/detail/275.jpg',
    categoryId: 6,
    amount: '5,500',
    originalAmount: '',
    sale: 0,
  },
  '276': {
    id: 276,
    title: '을지로에서 만든 뱃지. 바퀴',
    productImgSrc: 'public/image/product/big/276.jpg',
    detailImgSrc: 'public/image/product/detail/276.jpg',
    categoryId: 6,
    amount: '5,500',
    originalAmount: '',
    sale: 0,
  },
  '277': {
    id: 277,
    title: '을지로에서 만든 뱃지. 셔터',
    productImgSrc: 'public/image/product/big/277.jpg',
    detailImgSrc: 'public/image/product/detail/277.jpg',
    categoryId: 6,
    amount: '5,500',
    originalAmount: '',
    sale: 0,
  },
  '278': {
    id: 278,
    title: '을지로에서 만든 뱃지. 페인트통',
    productImgSrc: 'public/image/product/big/278.jpg',
    detailImgSrc: 'public/image/product/detail/278.jpg',
    categoryId: 6,
    amount: '5,500',
    originalAmount: '',
    sale: 0,
  },
  '279': {
    id: 279,
    title: '을지로에서 만든 뱃지. 사장',
    productImgSrc: 'public/image/product/big/279.jpg',
    detailImgSrc: 'public/image/product/detail/279.jpg',
    categoryId: 6,
    amount: '5,500',
    originalAmount: '',
    sale: 0,
  },
  '280': {
    id: 280,
    title: '을지로에서 만든 뱃지. 장인',
    productImgSrc: 'public/image/product/big/280.jpg',
    detailImgSrc: 'public/image/product/detail/280.jpg',
    categoryId: 6,
    amount: '5,500',
    originalAmount: '',
    sale: 0,
  },
  '281': {
    id: 281,
    title: '을지로에서 만든 은수저',
    productImgSrc: 'public/image/product/big/281.jpg',
    detailImgSrc: 'public/image/product/detail/281.jpg',
    categoryId: 6,
    amount: '120,000',
    originalAmount: '',
    sale: 0,
  },
  '282': {
    id: 282,
    title: '을지로에서 만든 쟁반',
    productImgSrc: 'public/image/product/big/282.jpg',
    detailImgSrc: 'public/image/product/detail/282.jpg',
    categoryId: 6,
    amount: '90,000',
    originalAmount: '',
    sale: 0,
  },
  '283': {
    id: 283,
    title: '을지로 사진 엽서',
    productImgSrc: 'public/image/product/big/283.jpg',
    detailImgSrc: 'public/image/product/detail/283.jpg',
    categoryId: 6,
    amount: '1,000',
    originalAmount: '',
    sale: 0,
  },
  '284': {
    id: 284,
    title: '을지로 사진 엽서. 정사각형',
    productImgSrc: 'public/image/product/big/284.jpg',
    detailImgSrc: 'public/image/product/detail/284.jpg',
    categoryId: 6,
    amount: '1,000',
    originalAmount: '',
    sale: 0,
  },
  '285': {
    id: 285,
    title: '을지로 사진 엽서. 파노라마형',
    productImgSrc: 'public/image/product/big/285.jpg',
    detailImgSrc: 'public/image/product/detail/285.jpg',
    categoryId: 6,
    amount: '1,000',
    originalAmount: '',
    sale: 0,
  },
  '286': {
    id: 286,
    title: '2021 일력. 오늘에 집중',
    productImgSrc: 'public/image/product/big/286.jpg',
    detailImgSrc: 'public/image/product/detail/286.jpg',
    categoryId: 2,
    amount: '1,000',
    originalAmount: '',
    sale: 0,
  },
  '287': {
    id: 287,
    title: '2021 다이어리. 오늘에 집중',
    productImgSrc: 'public/image/product/big/287.jpg',
    detailImgSrc: 'public/image/product/detail/287.jpg',
    categoryId: 1,
    amount: '1,000',
    originalAmount: '',
    sale: 0,
  },
  '288': {
    id: 288,
    title: '매거진F No.14 Beer',
    productImgSrc: 'public/image/product/big/288.jpg',
    detailImgSrc: 'public/image/product/detail/288.jpg',
    categoryId: 3,
    amount: '13,500',
    originalAmount: '15,000',
    sale: 10,
  },
  '289': {
    id: 289,
    title: '떡볶이 테이스팅 노트. 먹고쓰자',
    productImgSrc: 'public/image/product/big/289.jpg',
    detailImgSrc: 'public/image/product/detail/289.jpg',
    categoryId: 1,
    amount: '3,500',
    originalAmount: '',
    sale: 0,
  },
  '290': {
    id: 290,
    title: '요모포켓X배달이친구들 독고배달이 포켓',
    productImgSrc: 'public/image/product/big/290.jpg',
    detailImgSrc: 'public/image/product/detail/290.jpg',
    categoryId: 7,
    amount: '64,000',
    originalAmount: '',
    sale: 0,
  },
  '291': {
    id: 291,
    title: '요모포켓X배달이친구들 메이배달이 포켓',
    productImgSrc: 'public/image/product/big/291.jpg',
    detailImgSrc: 'public/image/product/detail/291.jpg',
    categoryId: 7,
    amount: '64,000',
    originalAmount: '',
    sale: 0,
  },
  '292': {
    id: 292,
    title: '요모포켓X배달이친구들 엉클배달이 포켓',
    productImgSrc: 'public/image/product/big/292.jpg',
    detailImgSrc: 'public/image/product/detail/292.jpg',
    categoryId: 7,
    amount: '64,000',
    originalAmount: '',
    sale: 0,
  },
  '293': {
    id: 293,
    title: '립볶이에디션',
    productImgSrc: 'public/image/product/big/293.jpg',
    detailImgSrc: 'public/image/product/detail/293.jpg',
    categoryId: 9,
    amount: '64,000',
    originalAmount: '',
    sale: 0,
  },
  '294': {
    id: 294,
    title: '떡볶이 키트.떡볶이가 필요해',
    productImgSrc: 'public/image/product/big/294.jpg',
    detailImgSrc: 'public/image/product/detail/294.jpg',
    categoryId: 8,
    amount: '11,000',
    originalAmount: '30,000',
    sale: 63,
  },
  '295': {
    id: 295,
    title: '매거진F No.15 Egg',
    productImgSrc: 'public/image/product/big/295.jpg',
    detailImgSrc: 'public/image/product/detail/295.jpg',
    categoryId: 3,
    amount: '13,500',
    originalAmount: '15,000',
    sale: 10,
  },
  '296': {
    id: 296,
    title: '스웨거X배민. 룸 스프레이 집중',
    productImgSrc: 'public/image/product/big/296.jpg',
    detailImgSrc: 'public/image/product/detail/296.jpg',
    categoryId: 9,
    amount: '15,200',
    originalAmount: '19,000',
    sale: 20,
  },
  '297': {
    id: 297,
    title: '화학표백을 하지 않은 재생지로 만든 메모잇',
    productImgSrc: 'public/image/product/big/297.jpg',
    detailImgSrc: 'public/image/product/detail/297.jpg',
    categoryId: 4,
    amount: '2,300',
    originalAmount: '',
    sale: 0,
  },
  '298': {
    id: 298,
    title: '커피찌꺼기를 재활용해 손으로 만든 연필',
    productImgSrc: 'public/image/product/big/298.jpg',
    detailImgSrc: 'public/image/product/detail/298.jpg',
    categoryId: 4,
    amount: '2,500',
    originalAmount: '',
    sale: 0,
  },
  '299': {
    id: 299,
    title: '재생지에 콩기름으로 인쇄한 일기장',
    productImgSrc: 'public/image/product/big/299.jpg',
    detailImgSrc: 'public/image/product/detail/299.jpg',
    categoryId: 4,
    amount: '3,500',
    originalAmount: '',
    sale: 0,
  },
  '300': {
    id: 300,
    title: '유해물질이 나오지 않는 지우개',
    productImgSrc: 'public/image/product/big/300.jpg',
    detailImgSrc: 'public/image/product/detail/300.jpg',
    categoryId: 4,
    amount: '1,500',
    originalAmount: '',
    sale: 0,
  },
  '301': {
    id: 301,
    title: '업사이클링 스탠드그립 세트. 맥주',
    productImgSrc: 'public/image/product/big/301.jpg',
    detailImgSrc: 'public/image/product/detail/301.jpg',
    categoryId: 9,
    amount: '18,900',
    originalAmount: '',
    sale: 0,
  },
  '302': {
    id: 302,
    title: '업사이클링 명함케이스. 맥주짠',
    productImgSrc: 'public/image/product/big/302.jpg',
    detailImgSrc: 'public/image/product/detail/302.jpg',
    categoryId: 9,
    amount: '16,900',
    originalAmount: '',
    sale: 0,
  },
  '303': {
    id: 303,
    title: '매거진F No.16 Namul',
    productImgSrc: 'public/image/product/big/303.jpg',
    detailImgSrc: 'public/image/product/detail/303.jpg',
    categoryId: 3,
    amount: '13,500',
    originalAmount: '15,000',
    sale: 10,
  },
  '304': {
    id: 304,
    title: '버추얼굿즈. 당신을 위한 의자',
    productImgSrc: 'public/image/product/big/304.jpg',
    detailImgSrc: 'public/image/product/detail/304.jpg',
    categoryId: 2,
    amount: '13,500',
    originalAmount: '',
    sale: 0,
  },
  '305': {
    id: 305,
    title: '플리츠마마X배달의민족. 텀블러백',
    productImgSrc: 'public/image/product/big/305.jpg',
    detailImgSrc: 'public/image/product/detail/305.jpg',
    categoryId: 4,
    amount: '29,000',
    originalAmount: '49,000',
    sale: 40,
  },
  '306': {
    id: 306,
    title: '세븐일레븐X배민. 저칼로리 아이스크림 3종',
    productImgSrc: 'public/image/product/big/306.jpg',
    detailImgSrc: 'public/image/product/detail/306.jpg',
    categoryId: 9,
    amount: '29,000',
    originalAmount: '',
    sale: 0,
  },
  '307': {
    id: 307,
    title: '매거진F No.17 Icecream',
    productImgSrc: 'public/image/product/big/307.jpg',
    detailImgSrc: 'public/image/product/detail/307.jpg',
    categoryId: 3,
    amount: '13,500',
    originalAmount: '15,000',
    sale: 10,
  },
};
